"""Golden-data numeric parity with VTTrac.jl v2.0.0.

Each tests/data/golden/*.npz case was generated by tools/gen_golden.jl running
the reference Julia implementation. Discrete outputs (status, count, t_index)
must match exactly; continuous outputs are compared with the tolerances 
(rtol=1e-5/atol=1e-6 for x/y/vx/vy, rtol=1e-4 for score, to accommodate Float32 
accumulation-order differences between the two languages).
"""

import glob
import json
import os

import numpy as np
import pytest

import pyvttrac as vt

GOLDEN_DIR = os.path.join(os.path.dirname(__file__), "data", "golden")
GOLDEN_FILES = sorted(glob.glob(os.path.join(GOLDEN_DIR, "*.npz")))


@pytest.fixture(scope="session", autouse=True)
def _require_golden_data():
    if not GOLDEN_FILES:
        pytest.skip(
            "No golden data found under tests/data/golden/. Generate it with "
            "`julia --project=tools tools/gen_golden.jl` (see tools/gen_golden.jl)."
        )


def _run_case(path):
    d = np.load(path)
    params = json.loads(bytes(d["params_json"]).decode("utf-8"))

    z = d["z"]
    t = d["t"]
    mask = d["mask"] if "mask" in d.files else None

    x0 = d["x0_in"]
    y0 = d["y0_in"]
    t0 = d["tid0_in"].astype(np.int64)

    first_guess = None
    if "vyg_in" in d.files:
        first_guess = (d["vyg_in"], d["vxg_in"])

    subgrid = None
    if params["subgrid"]:
        subgrid = "gaussian" if params["subgrid_gaus"] else "paraboloid"

    max_velocity_change = None
    if params["vxch"] is not None and params["vych"] is not None:
        max_velocity_change = (params["vych"], params["vxch"])

    # exercise both ways ixhw/iyhw can be specified, matching how each golden
    # case was originally set up in Julia (via vxhw/vyhw, or directly)
    search_kwargs = {}
    if params["vxhw"] is not None:
        search_kwargs["search_velocity"] = (params["vyhw"], params["vxhw"])
    else:
        search_kwargs["search_radius"] = (params["iyhw"], params["ixhw"])

    diagnostics = bool(params["out_subimage"] or params["out_score_ary"])

    res = vt.track(
        z, x0, y0, t0=t0,
        template=(params["nsy"], params["nsx"]),
        nsteps=params["ntrac"],
        time=t,
        mask=mask,
        method=params["score_method"],
        subgrid=subgrid,
        step=params["itstep"],
        min_score=(params["Sth0"], params["Sth1"]),
        max_velocity_change=max_velocity_change,
        min_contrast=params["Cth"],
        min_peak_prominence=params["peak_inside_th"],
        fixed_template=params["use_init_temp"],
        min_samples=params["min_samples"],
        first_guess=first_guess,
        missing_value=params["zmiss"],
        diagnostics=diagnostics,
        **search_kwargs,
    )
    return res, d, params


@pytest.mark.parametrize("path", GOLDEN_FILES, ids=[os.path.basename(p) for p in GOLDEN_FILES])
def test_golden_discrete_outputs(path):
    res, d, _ = _run_case(path)
    np.testing.assert_array_equal(res.count, d["count"], err_msg="count")
    np.testing.assert_array_equal(res.status, d["status"], err_msg="status")
    np.testing.assert_array_equal(res.t_index, d["t_index"], err_msg="t_index")


@pytest.mark.parametrize("path", GOLDEN_FILES, ids=[os.path.basename(p) for p in GOLDEN_FILES])
def test_golden_continuous_outputs(path):
    res, d, _ = _run_case(path)
    for name in ("x", "y", "vx", "vy"):
        np.testing.assert_allclose(
            getattr(res, name), d[name], rtol=1e-5, atol=1e-6, equal_nan=True, err_msg=name
        )
    np.testing.assert_allclose(
        res.score, d["score"], rtol=1e-4, atol=1e-6, equal_nan=True, err_msg="score"
    )


@pytest.mark.parametrize("path", GOLDEN_FILES, ids=[os.path.basename(p) for p in GOLDEN_FILES])
def test_golden_diagnostics(path):
    if "zss" not in np.load(path).files and "score_ary" not in np.load(path).files:
        pytest.skip("case has no diagnostics output")
    res, d, params = _run_case(path)

    if "zss" in d.files:
        # golden zss is (ntrac+1, nsy, nsx, n) (Julia axis order); pyvttrac's
        # templates is (nsteps+1, nsy, nsx, *seed_shape). Untracked steps are
        # left at each side's fill value (0.0 in both, since none of the
        # diagnostics golden cases set a missing_value) -- status/count
        # parity (checked above) guarantees the written/unwritten regions
        # line up, so a direct tolerance comparison is valid everywhere.
        golden_zss = d["zss"]
        np.testing.assert_allclose(
            res.templates.reshape(golden_zss.shape), golden_zss,
            rtol=1e-5, atol=1e-6, err_msg="templates/zss",
        )
    if "score_ary" in d.files:
        golden_scr = d["score_ary"]
        # Looser atol than the primary `score` field: this array holds every
        # candidate window's score (not just the selected peak), so it has
        # many more near-zero entries where Float32 accumulation-order noise
        # shows up as a larger relative error.
        np.testing.assert_allclose(
            res.score_grids.reshape(golden_scr.shape), golden_scr,
            rtol=1e-4, atol=1e-5, err_msg="score_grids/score_ary",
        )


def test_all_status_codes_covered_by_golden_suite():
    """Sanity check on the golden data itself."""
    seen = set()
    for path in GOLDEN_FILES:
        d = np.load(path)
        seen.update(int(s) for s in np.unique(d["status"]))
    assert seen >= set(range(10)), f"golden suite is missing status codes: {set(range(10)) - seen}"
